// <auto-generated />
using System;
using EmployeeRecognition.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeRecognition.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711050000_AddRecognitionReactions")]
    partial class AddRecognitionReactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeRecognition.API.Models.AwardCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ManagerOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AwardCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Outstanding performance and dedication",
                            Icon = "⭐",
                            ManagerOnly = true,
                            Name = "Star of the Month",
                            Points = 500
                        },
                        new
                        {
                            Id = 2,
                            Description = "Consistently exceeds expectations",
                            Icon = "🏆",
                            ManagerOnly = true,
                            Name = "Employee of the Month",
                            Points = 1000
                        },
                        new
                        {
                            Id = 3,
                            Description = "Exceptional collaboration and teamwork",
                            Icon = "🤝",
                            ManagerOnly = false,
                            Name = "Team Player",
                            Points = 200
                        },
                        new
                        {
                            Id = 4,
                            Description = "Creative solutions and new ideas",
                            Icon = "💡",
                            ManagerOnly = true,
                            Name = "Innovation Champion",
                            Points = 300
                        },
                        new
                        {
                            Id = 5,
                            Description = "Goes above and beyond to help others",
                            Icon = "🙌",
                            ManagerOnly = false,
                            Name = "Helping Hand",
                            Points = 150
                        },
                        new
                        {
                            Id = 6,
                            Description = "Rapid skill development and growth",
                            Icon = "🚀",
                            ManagerOnly = false,
                            Name = "Quick Learner",
                            Points = 100
                        });
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.HasIndex("TotalPoints");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "AU",
                            Department = "HR",
                            Email = "admin@company.com",
                            IsActive = true,
                            Location = "",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$3qmBklJIBoFmouV9jjSc7eiVKAqJ7q8c8/bqGJt3wE7bZwZ2GzTT2",
                            Role = "HR Manager",
                            TotalPoints = 0,
                            UserRole = "admin"
                        });
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Recognition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ToEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FromEmployeeId", "CreatedAt");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("ToEmployeeId", "CreatedAt");

                    b.HasIndex("ToEmployeeId", "Type", "Status");

                    b.HasIndex("Type", "Status", "CreatedAt");

                    b.ToTable("Recognitions");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RecognitionComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecognitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RecognitionId", "CreatedAt");

                    b.ToTable("RecognitionComments");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RecognitionLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RecognitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RecognitionId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("RecognitionLikes");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RewardRedemption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "CreatedAt");

                    b.ToTable("RewardRedemptions");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Employee", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Notification", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Recognition", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.AwardCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EmployeeRecognition.API.Models.Employee", "FromEmployee")
                        .WithMany("RecognitionsGiven")
                        .HasForeignKey("FromEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeRecognition.API.Models.Employee", "ToEmployee")
                        .WithMany("RecognitionsReceived")
                        .HasForeignKey("ToEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FromEmployee");

                    b.Navigation("ToEmployee");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RecognitionComment", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeRecognition.API.Models.Recognition", "Recognition")
                        .WithMany("Comments")
                        .HasForeignKey("RecognitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Recognition");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RecognitionLike", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeRecognition.API.Models.Recognition", "Recognition")
                        .WithMany("Likes")
                        .HasForeignKey("RecognitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Recognition");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RewardRedemption", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Employee", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("RecognitionsGiven");

                    b.Navigation("RecognitionsReceived");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Recognition", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
