// <auto-generated />
using System;
using EmployeeRecognition.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeRecognition.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeRecognition.API.Models.AwardCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccumulationIncrement")
                        .HasColumnType("int");

                    b.Property<int>("AccumulationThreshold")
                        .HasColumnType("int");

                    b.Property<int>("ApprovalLevel")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAccumulative")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagerOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("RecentJoinerMaxMonths")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresRecentJoiner")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AwardCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccumulationIncrement = 0,
                            AccumulationThreshold = 0,
                            ApprovalLevel = 0,
                            Description = "A simple gesture can brighten up someone's day — give a shout-out to recognize a peer for their work.",
                            Icon = "👏",
                            IsAccumulative = false,
                            ManagerOnly = false,
                            Name = "Kudos",
                            Points = 0,
                            RecentJoinerMaxMonths = 0,
                            RequiresRecentJoiner = false
                        },
                        new
                        {
                            Id = 2,
                            AccumulationIncrement = 0,
                            AccumulationThreshold = 0,
                            ApprovalLevel = 1,
                            Description = "Any significant effort towards producing customer delight, internal or external, adding value to customers or stakeholders.",
                            Icon = "🎯",
                            IsAccumulative = false,
                            ManagerOnly = true,
                            Name = "Customer Focus",
                            Points = 500,
                            RecentJoinerMaxMonths = 0,
                            RequiresRecentJoiner = false
                        },
                        new
                        {
                            Id = 3,
                            AccumulationIncrement = 0,
                            AccumulationThreshold = 0,
                            ApprovalLevel = 1,
                            Description = "Operating effectively even when things are not certain, or the way forward is not clear.",
                            Icon = "🧭",
                            IsAccumulative = false,
                            ManagerOnly = true,
                            Name = "Manages Ambiguity",
                            Points = 500,
                            RecentJoinerMaxMonths = 0,
                            RequiresRecentJoiner = false
                        },
                        new
                        {
                            Id = 4,
                            AccumulationIncrement = 100,
                            AccumulationThreshold = 500,
                            ApprovalLevel = 1,
                            Description = "Learning & development award — points accumulate 100 per completed training, redeemable once you reach 500.",
                            Icon = "📚",
                            IsAccumulative = true,
                            ManagerOnly = true,
                            Name = "Self Development",
                            Points = 100,
                            RecentJoinerMaxMonths = 0,
                            RequiresRecentJoiner = false
                        },
                        new
                        {
                            Id = 5,
                            AccumulationIncrement = 0,
                            AccumulationThreshold = 0,
                            ApprovalLevel = 1,
                            Description = "Taking on new opportunities and tough challenges with a sense of urgency, high energy and enthusiasm.",
                            Icon = "⚡",
                            IsAccumulative = false,
                            ManagerOnly = true,
                            Name = "Action Oriented",
                            Points = 500,
                            RecentJoinerMaxMonths = 0,
                            RequiresRecentJoiner = false
                        },
                        new
                        {
                            Id = 6,
                            AccumulationIncrement = 0,
                            AccumulationThreshold = 0,
                            ApprovalLevel = 1,
                            Description = "Taking responsibility, owning up to commitments and being answerable for your actions.",
                            Icon = "🛡️",
                            IsAccumulative = false,
                            ManagerOnly = true,
                            Name = "Ensures Accountability",
                            Points = 500,
                            RecentJoinerMaxMonths = 0,
                            RequiresRecentJoiner = false
                        },
                        new
                        {
                            Id = 7,
                            AccumulationIncrement = 0,
                            AccumulationThreshold = 0,
                            ApprovalLevel = 1,
                            Description = "Consistently achieving results, even under tough circumstances.",
                            Icon = "📈",
                            IsAccumulative = false,
                            ManagerOnly = true,
                            Name = "Drives Result",
                            Points = 500,
                            RecentJoinerMaxMonths = 0,
                            RequiresRecentJoiner = false
                        },
                        new
                        {
                            Id = 8,
                            AccumulationIncrement = 0,
                            AccumulationThreshold = 0,
                            ApprovalLevel = 1,
                            Description = "Innovative solution to overcome a challenge, or innovation of process.",
                            Icon = "💡",
                            IsAccumulative = false,
                            ManagerOnly = true,
                            Name = "Innovation Award",
                            Points = 500,
                            RecentJoinerMaxMonths = 0,
                            RequiresRecentJoiner = false
                        },
                        new
                        {
                            Id = 9,
                            AccumulationIncrement = 0,
                            AccumulationThreshold = 0,
                            ApprovalLevel = 2,
                            Description = "Demonstrate exemplary individual achievements, contributions, and outstanding job performance in a very demanding project or delivery.",
                            Icon = "🏆",
                            IsAccumulative = false,
                            ManagerOnly = true,
                            Name = "Employee of the Quarter",
                            Points = 2000,
                            RecentJoinerMaxMonths = 0,
                            RequiresRecentJoiner = false
                        },
                        new
                        {
                            Id = 10,
                            AccumulationIncrement = 0,
                            AccumulationThreshold = 0,
                            ApprovalLevel = 2,
                            Description = "For new joinees — recognizes strong impact within their first 6 months.",
                            Icon = "🌟",
                            IsAccumulative = false,
                            ManagerOnly = true,
                            Name = "Rising Star",
                            Points = 3000,
                            RecentJoinerMaxMonths = 6,
                            RequiresRecentJoiner = true
                        });
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SelfDevelopmentAccumulatedPoints")
                        .HasColumnType("int");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.HasIndex("TotalPoints");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "AU",
                            Department = "HR",
                            Email = "admin@company.com",
                            IsActive = true,
                            Location = "",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$3qmBklJIBoFmouV9jjSc7eiVKAqJ7q8c8/bqGJt3wE7bZwZ2GzTT2",
                            Role = "HR Manager",
                            TotalPoints = 0,
                            UserRole = "admin"
                        });
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Recognition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ToEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FromEmployeeId", "CreatedAt");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("ToEmployeeId", "CreatedAt");

                    b.HasIndex("ToEmployeeId", "Type", "Status");

                    b.HasIndex("Type", "Status", "CreatedAt");

                    b.ToTable("Recognitions");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RecognitionComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecognitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RecognitionId", "CreatedAt");

                    b.ToTable("RecognitionComments");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RecognitionLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RecognitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RecognitionId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("RecognitionLikes");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RewardRedemption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "CreatedAt");

                    b.ToTable("RewardRedemptions");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Employee", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Notification", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Recognition", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.AwardCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EmployeeRecognition.API.Models.Employee", "FromEmployee")
                        .WithMany("RecognitionsGiven")
                        .HasForeignKey("FromEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeRecognition.API.Models.Employee", "ToEmployee")
                        .WithMany("RecognitionsReceived")
                        .HasForeignKey("ToEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FromEmployee");

                    b.Navigation("ToEmployee");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RecognitionComment", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeRecognition.API.Models.Recognition", "Recognition")
                        .WithMany("Comments")
                        .HasForeignKey("RecognitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Recognition");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RecognitionLike", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeRecognition.API.Models.Recognition", "Recognition")
                        .WithMany("Likes")
                        .HasForeignKey("RecognitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Recognition");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RewardRedemption", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Employee", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("RecognitionsGiven");

                    b.Navigation("RecognitionsReceived");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Recognition", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
