// <auto-generated />
using System;
using EmployeeRecognition.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeRecognition.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716063315_AddNominationEnhancements")]
    partial class AddNominationEnhancements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeRecognition.API.Models.AwardCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AwardType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ManagerOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AwardCategories");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            AwardType = "appreciation",
                            Description = "Exceptional collaboration and teamwork",
                            Icon = "🤝",
                            ManagerOnly = false,
                            Name = "Team Player",
                            Points = 200
                        },
                        new
                        {
                            Id = 5,
                            AwardType = "appreciation",
                            Description = "Goes above and beyond to help others",
                            Icon = "🙌",
                            ManagerOnly = false,
                            Name = "Helping Hand",
                            Points = 150
                        },
                        new
                        {
                            Id = 6,
                            AwardType = "appreciation",
                            Description = "Rapid skill development and growth",
                            Icon = "🚀",
                            ManagerOnly = false,
                            Name = "Quick Learner",
                            Points = 100
                        },
                        new
                        {
                            Id = 7,
                            AwardType = "spot",
                            Description = "Customer-centric dedication and service",
                            Icon = "🎯",
                            ManagerOnly = true,
                            Name = "Customer Focus",
                            Points = 500
                        },
                        new
                        {
                            Id = 8,
                            AwardType = "spot",
                            Description = "Succeeds even in complex or uncertain conditions",
                            Icon = "🌀",
                            ManagerOnly = true,
                            Name = "Manages Ambiguity",
                            Points = 500
                        },
                        new
                        {
                            Id = 9,
                            AwardType = "spot",
                            Description = "Commitment to learning and self-improvement",
                            Icon = "📚",
                            ManagerOnly = true,
                            Name = "Self Development",
                            Points = 500
                        },
                        new
                        {
                            Id = 10,
                            AwardType = "spot",
                            Description = "Proactive drive and bias for action",
                            Icon = "⚡",
                            ManagerOnly = true,
                            Name = "Action Oriented",
                            Points = 500
                        },
                        new
                        {
                            Id = 11,
                            AwardType = "spot",
                            Description = "Takes ownership and follows through",
                            Icon = "🤝",
                            ManagerOnly = true,
                            Name = "Ensures Accountability",
                            Points = 500
                        },
                        new
                        {
                            Id = 12,
                            AwardType = "spot",
                            Description = "Focus on output and results",
                            Icon = "📈",
                            ManagerOnly = true,
                            Name = "Drives Result",
                            Points = 500
                        },
                        new
                        {
                            Id = 13,
                            AwardType = "spot",
                            Description = "Exceptional innovation and creative solutions",
                            Icon = "💡",
                            ManagerOnly = true,
                            Name = "Innovation Award (BA)",
                            Points = 500
                        },
                        new
                        {
                            Id = 14,
                            AwardType = "performance",
                            Description = "Outstanding performance this quarter",
                            Icon = "🏆",
                            ManagerOnly = true,
                            Name = "Employee of the Quarter",
                            Points = 2000
                        },
                        new
                        {
                            Id = 15,
                            AwardType = "performance",
                            Description = "Promising talent within first 6 months",
                            Icon = "✨",
                            ManagerOnly = true,
                            Name = "Rising Star (BA)",
                            Points = 3000
                        });
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.HasIndex("TotalPoints");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "AU",
                            Department = "HR",
                            Email = "admin@company.com",
                            IsActive = true,
                            JoiningDate = new DateOnly(2021, 1, 1),
                            Location = "Sweden",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$KTarDjBgVZcdQJ5JQ3I.K.OoIBSBdnirmSl8Qg/N7Os8F3/FWLv9.",
                            Role = "HR Manager",
                            TotalPoints = 0,
                            UserRole = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "BA",
                            Department = "BU 1",
                            Email = "bu.manager.a@company.com",
                            IsActive = true,
                            JoiningDate = new DateOnly(2021, 1, 1),
                            Location = "Sweden",
                            ManagerId = 1,
                            Name = "BU Manager A",
                            PasswordHash = "$2a$11$KTarDjBgVZcdQJ5JQ3I.K.OoIBSBdnirmSl8Qg/N7Os8F3/FWLv9.",
                            Role = "BU Head",
                            TotalPoints = 0,
                            UserRole = "manager"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "BB",
                            Department = "BU 2",
                            Email = "bu.manager.b@company.com",
                            IsActive = true,
                            JoiningDate = new DateOnly(2021, 1, 1),
                            Location = "Sweden",
                            ManagerId = 1,
                            Name = "BU Manager B",
                            PasswordHash = "$2a$11$KTarDjBgVZcdQJ5JQ3I.K.OoIBSBdnirmSl8Qg/N7Os8F3/FWLv9.",
                            Role = "BU Head",
                            TotalPoints = 0,
                            UserRole = "manager"
                        },
                        new
                        {
                            Id = 4,
                            Avatar = "C1",
                            Department = "BU 1",
                            Email = "cu.manager.a1@company.com",
                            IsActive = true,
                            JoiningDate = new DateOnly(2022, 1, 1),
                            Location = "Sweden",
                            ManagerId = 2,
                            Name = "CU Manager A1",
                            PasswordHash = "$2a$11$KTarDjBgVZcdQJ5JQ3I.K.OoIBSBdnirmSl8Qg/N7Os8F3/FWLv9.",
                            Role = "CU Lead",
                            TotalPoints = 0,
                            UserRole = "manager"
                        },
                        new
                        {
                            Id = 5,
                            Avatar = "C2",
                            Department = "BU 1",
                            Email = "cu.manager.a2@company.com",
                            IsActive = true,
                            JoiningDate = new DateOnly(2022, 1, 1),
                            Location = "Sweden",
                            ManagerId = 2,
                            Name = "CU Manager A2",
                            PasswordHash = "$2a$11$KTarDjBgVZcdQJ5JQ3I.K.OoIBSBdnirmSl8Qg/N7Os8F3/FWLv9.",
                            Role = "CU Lead",
                            TotalPoints = 0,
                            UserRole = "manager"
                        },
                        new
                        {
                            Id = 6,
                            Avatar = "C3",
                            Department = "BU 2",
                            Email = "cu.manager.b1@company.com",
                            IsActive = true,
                            JoiningDate = new DateOnly(2022, 1, 1),
                            Location = "Sweden",
                            ManagerId = 3,
                            Name = "CU Manager B1",
                            PasswordHash = "$2a$11$KTarDjBgVZcdQJ5JQ3I.K.OoIBSBdnirmSl8Qg/N7Os8F3/FWLv9.",
                            Role = "CU Lead",
                            TotalPoints = 0,
                            UserRole = "manager"
                        },
                        new
                        {
                            Id = 7,
                            Avatar = "HA",
                            Department = "BU 1",
                            Email = "harika@company.com",
                            IsActive = true,
                            JoiningDate = new DateOnly(2025, 1, 1),
                            Location = "Sweden",
                            ManagerId = 4,
                            Name = "Harika",
                            PasswordHash = "$2a$11$KTarDjBgVZcdQJ5JQ3I.K.OoIBSBdnirmSl8Qg/N7Os8F3/FWLv9.",
                            Role = "Senior Engineer",
                            TotalPoints = 0,
                            UserRole = "employee"
                        },
                        new
                        {
                            Id = 8,
                            Avatar = "VI",
                            Department = "BU 1",
                            Email = "vishwas@company.com",
                            IsActive = true,
                            JoiningDate = new DateOnly(2026, 5, 16),
                            Location = "Sweden",
                            ManagerId = 5,
                            Name = "Vishwas",
                            PasswordHash = "$2a$11$KTarDjBgVZcdQJ5JQ3I.K.OoIBSBdnirmSl8Qg/N7Os8F3/FWLv9.",
                            Role = "Developer",
                            TotalPoints = 0,
                            UserRole = "employee"
                        },
                        new
                        {
                            Id = 9,
                            Avatar = "RA",
                            Department = "BU 2",
                            Email = "rahul@company.com",
                            IsActive = true,
                            JoiningDate = new DateOnly(2025, 1, 1),
                            Location = "Sweden",
                            ManagerId = 6,
                            Name = "Rahul",
                            PasswordHash = "$2a$11$KTarDjBgVZcdQJ5JQ3I.K.OoIBSBdnirmSl8Qg/N7Os8F3/FWLv9.",
                            Role = "Developer",
                            TotalPoints = 0,
                            UserRole = "employee"
                        },
                        new
                        {
                            Id = 10,
                            Avatar = "AN",
                            Department = "BU 1",
                            Email = "anjali@company.com",
                            IsActive = true,
                            JoiningDate = new DateOnly(2026, 6, 16),
                            Location = "Sweden",
                            ManagerId = 4,
                            Name = "Anjali",
                            PasswordHash = "$2a$11$KTarDjBgVZcdQJ5JQ3I.K.OoIBSBdnirmSl8Qg/N7Os8F3/FWLv9.",
                            Role = "Developer",
                            TotalPoints = 0,
                            UserRole = "employee"
                        });
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.NominationAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecognitionId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecognitionId");

                    b.ToTable("NominationAudits");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.PointsAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecognitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RecognitionId");

                    b.ToTable("PointsAudits");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Recognition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AwardCycle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BUDecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BUManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FromEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("HRAdminId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HRDecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ToEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BUManagerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("HRAdminId");

                    b.HasIndex("FromEmployeeId", "CreatedAt");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("ToEmployeeId", "CreatedAt");

                    b.HasIndex("ToEmployeeId", "Type", "Status");

                    b.HasIndex("Type", "Status", "CreatedAt");

                    b.ToTable("Recognitions");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RecognitionComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecognitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RecognitionId", "CreatedAt");

                    b.ToTable("RecognitionComments");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RecognitionLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RecognitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RecognitionId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("RecognitionLikes");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RewardRedemption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "CreatedAt");

                    b.ToTable("RewardRedemptions");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Employee", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.NominationAudit", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Recognition", "Recognition")
                        .WithMany("Audits")
                        .HasForeignKey("RecognitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recognition");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Notification", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.PointsAudit", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeRecognition.API.Models.Recognition", "Recognition")
                        .WithMany()
                        .HasForeignKey("RecognitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("Recognition");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Recognition", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "BUManager")
                        .WithMany()
                        .HasForeignKey("BUManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EmployeeRecognition.API.Models.AwardCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EmployeeRecognition.API.Models.Employee", "FromEmployee")
                        .WithMany("RecognitionsGiven")
                        .HasForeignKey("FromEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeRecognition.API.Models.Employee", "HRAdmin")
                        .WithMany()
                        .HasForeignKey("HRAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EmployeeRecognition.API.Models.Employee", "ToEmployee")
                        .WithMany("RecognitionsReceived")
                        .HasForeignKey("ToEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BUManager");

                    b.Navigation("Category");

                    b.Navigation("FromEmployee");

                    b.Navigation("HRAdmin");

                    b.Navigation("ToEmployee");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RecognitionComment", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeRecognition.API.Models.Recognition", "Recognition")
                        .WithMany("Comments")
                        .HasForeignKey("RecognitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Recognition");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RecognitionLike", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeRecognition.API.Models.Recognition", "Recognition")
                        .WithMany("Likes")
                        .HasForeignKey("RecognitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Recognition");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.RewardRedemption", b =>
                {
                    b.HasOne("EmployeeRecognition.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Employee", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("RecognitionsGiven");

                    b.Navigation("RecognitionsReceived");
                });

            modelBuilder.Entity("EmployeeRecognition.API.Models.Recognition", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
